name: cicd-V1
on: push

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: |
        cd springboot-CICD
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd springboot-CICD
        ./gradlew build